name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: WarenGonzaga
          template: classic
          base: header, activity, community
          config_timezone: Asia/Manila

          # Language plugin
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage

          # Achievement plugin
          plugin_achievements: yes
          plugin_achievements_threshold: B

          # Notable contributions
          plugin_notable: yes
          plugin_notable_filter: stars:>150
          plugin_notable_repositories: yes
